// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @altersend/remembered-peer
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.remoteDevicePubkey)
    c.string.preencode(state, m.rendezvousTopic)
    c.string.preencode(state, m.displayName)
    c.string.preencode(state, m.deviceType)
    state.end++ // max flag is 4 so always one byte
    c.uint.preencode(state, m.pairedAt)
    c.uint.preencode(state, m.lastSeenAt)
  },
  encode(state, m) {
    const flags = (m.isMine ? 1 : 0) | (m.autoAccept ? 2 : 0) | (m.blocked ? 4 : 0)

    c.string.encode(state, m.remoteDevicePubkey)
    c.string.encode(state, m.rendezvousTopic)
    c.string.encode(state, m.displayName)
    c.string.encode(state, m.deviceType)
    c.uint.encode(state, flags)
    c.uint.encode(state, m.pairedAt)
    c.uint.encode(state, m.lastSeenAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      remoteDevicePubkey: r0,
      rendezvousTopic: r1,
      displayName: r2,
      deviceType: r3,
      isMine: (flags & 1) !== 0,
      autoAccept: (flags & 2) !== 0,
      blocked: (flags & 4) !== 0,
      pairedAt: c.uint.decode(state),
      lastSeenAt: c.uint.decode(state)
    }
  }
}

// @altersend/remembered-peer/hyperdb#0
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.rendezvousTopic)
    c.string.preencode(state, m.displayName)
    c.string.preencode(state, m.deviceType)
    state.end++ // max flag is 4 so always one byte
    c.uint.preencode(state, m.pairedAt)
    c.uint.preencode(state, m.lastSeenAt)
  },
  encode(state, m) {
    const flags = (m.isMine ? 1 : 0) | (m.autoAccept ? 2 : 0) | (m.blocked ? 4 : 0)

    c.string.encode(state, m.rendezvousTopic)
    c.string.encode(state, m.displayName)
    c.string.encode(state, m.deviceType)
    c.uint.encode(state, flags)
    c.uint.encode(state, m.pairedAt)
    c.uint.encode(state, m.lastSeenAt)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      remoteDevicePubkey: null,
      rendezvousTopic: r1,
      displayName: r2,
      deviceType: r3,
      isMine: (flags & 1) !== 0,
      autoAccept: (flags & 2) !== 0,
      blocked: (flags & 4) !== 0,
      pairedAt: c.uint.decode(state),
      lastSeenAt: c.uint.decode(state)
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@altersend/remembered-peer':
      return encoding0
    case '@altersend/remembered-peer/hyperdb#0':
      return encoding1
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
